# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compiler.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Compiler(object):
    def setupUi(self, Compiler):
        Compiler.setObjectName("Compiler")
        Compiler.resize(800, 700)
        Compiler.setMaximumSize(QtCore.QSize(800, 700))
        self.centralwidget = QtWidgets.QWidget(Compiler)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(0, 29, 800, 671))
        self.textEdit.setMaximumSize(QtCore.QSize(800, 700))
        self.textEdit.setMouseTracking(False)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setStyleSheet("color: rgb(85, 170, 127);")
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 41, 28))
        self.pushButton.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 0, 31, 28))
        self.pushButton_2.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/open.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 0, 31, 28))
        self.pushButton_3.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 0, 31, 28))
        self.pushButton_4.setStyleSheet("background-color: rgb(189, 189, 189);")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Images/compile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setObjectName("pushButton_4")
        Compiler.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Compiler)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        Compiler.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Compiler)
        self.statusbar.setObjectName("statusbar")
        Compiler.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(Compiler)
        self.actionNew.setEnabled(True)
        self.actionNew.setIcon(icon)
        self.actionNew.setShortcutContext(QtCore.Qt.WindowShortcut)
        self.actionNew.setVisible(True)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(Compiler)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(Compiler)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(Compiler)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(Compiler)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Images/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon5)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCut = QtWidgets.QAction(Compiler)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Images/Cut-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon6)
        self.actionCut.setObjectName("actionCut")
        self.actionPaste = QtWidgets.QAction(Compiler)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Images/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon7)
        self.actionPaste.setObjectName("actionPaste")
        self.actionUndo = QtWidgets.QAction(Compiler)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../Images/Undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon8)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(Compiler)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../Images/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon9)
        self.actionRedo.setObjectName("actionRedo")
        self.actionBold = QtWidgets.QAction(Compiler)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../Images/bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon10)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtWidgets.QAction(Compiler)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../Images/italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalic.setIcon(icon11)
        self.actionItalic.setObjectName("actionItalic")
        self.actionUndeline = QtWidgets.QAction(Compiler)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../Images/underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndeline.setIcon(icon12)
        self.actionUndeline.setObjectName("actionUndeline")
        self.actionCenter = QtWidgets.QAction(Compiler)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../Images/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCenter.setIcon(icon13)
        self.actionCenter.setObjectName("actionCenter")
        self.actionCenter_2 = QtWidgets.QAction(Compiler)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../Images/center.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCenter_2.setIcon(icon14)
        self.actionCenter_2.setObjectName("actionCenter_2")
        self.actionRight = QtWidgets.QAction(Compiler)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("../Images/right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRight.setIcon(icon15)
        self.actionRight.setObjectName("actionRight")
        self.actionJustify = QtWidgets.QAction(Compiler)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("../Images/justify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJustify.setIcon(icon16)
        self.actionJustify.setObjectName("actionJustify")
        self.actionAbout = QtWidgets.QAction(Compiler)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("../Images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon17)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCompile = QtWidgets.QAction(Compiler)
        self.actionCompile.setIcon(icon3)
        self.actionCompile.setObjectName("actionCompile")
        self.menuNew.addAction(self.actionNew)
        self.menuNew.addAction(self.actionOpen)
        self.menuNew.addAction(self.actionSave)
        self.menuNew.addAction(self.actionCompile)
        self.menuNew.addSeparator()
        self.menuNew.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(Compiler)
        QtCore.QMetaObject.connectSlotsByName(Compiler)

    def retranslateUi(self, Compiler):
        _translate = QtCore.QCoreApplication.translate
        Compiler.setWindowTitle(_translate("Compiler", "Compiler"))
        self.menuNew.setTitle(_translate("Compiler", "File"))
        self.menuEdit.setTitle(_translate("Compiler", "Edit"))
        self.menuHelp.setTitle(_translate("Compiler", "Help"))
        self.actionNew.setText(_translate("Compiler", "New"))
        self.actionNew.setShortcut(_translate("Compiler", "Ctrl+N"))
        self.actionOpen.setText(_translate("Compiler", "Open"))
        self.actionOpen.setShortcut(_translate("Compiler", "Ctrl+O"))
        self.actionSave.setText(_translate("Compiler", "Save"))
        self.actionSave.setShortcut(_translate("Compiler", "Ctrl+S"))
        self.actionExit.setText(_translate("Compiler", "Exit"))
        self.actionExit.setShortcut(_translate("Compiler", "Esc"))
        self.actionCopy.setText(_translate("Compiler", "Copy"))
        self.actionCopy.setShortcut(_translate("Compiler", "Ctrl+C"))
        self.actionCut.setText(_translate("Compiler", "Cut"))
        self.actionCut.setShortcut(_translate("Compiler", "Ctrl+X"))
        self.actionPaste.setText(_translate("Compiler", "Paste"))
        self.actionPaste.setShortcut(_translate("Compiler", "Ctrl+P"))
        self.actionUndo.setText(_translate("Compiler", "Undo"))
        self.actionUndo.setShortcut(_translate("Compiler", "Ctrl+Z"))
        self.actionRedo.setText(_translate("Compiler", "Redo"))
        self.actionRedo.setShortcut(_translate("Compiler", "Ctrl+Y"))
        self.actionBold.setText(_translate("Compiler", "Bold"))
        self.actionBold.setShortcut(_translate("Compiler", "Ctrl+B"))
        self.actionItalic.setText(_translate("Compiler", "Italic"))
        self.actionItalic.setShortcut(_translate("Compiler", "Ctrl+I"))
        self.actionUndeline.setText(_translate("Compiler", "Undeline"))
        self.actionUndeline.setShortcut(_translate("Compiler", "Ctrl+U"))
        self.actionCenter.setText(_translate("Compiler", "Left"))
        self.actionCenter.setShortcut(_translate("Compiler", "Ctrl+Shift+L"))
        self.actionCenter_2.setText(_translate("Compiler", "Center"))
        self.actionCenter_2.setShortcut(_translate("Compiler", "Ctrl+Shift+C"))
        self.actionRight.setText(_translate("Compiler", "Right"))
        self.actionRight.setShortcut(_translate("Compiler", "Ctrl+Shift+R"))
        self.actionJustify.setText(_translate("Compiler", "Justify"))
        self.actionJustify.setShortcut(_translate("Compiler", "Ctrl+Shift+J"))
        self.actionAbout.setText(_translate("Compiler", "About"))
        self.actionAbout.setShortcut(_translate("Compiler", "F1"))
        self.actionCompile.setText(_translate("Compiler", "Compile"))
        self.actionCompile.setShortcut(_translate("Compiler", "F5"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Compiler = QtWidgets.QMainWindow()
    ui = Ui_Compiler()
    ui.setupUi(Compiler)
    s_max = Compiler.maximumSize();
    Compiler.setFixedSize(s_max);
    Compiler.show()
    sys.exit(app.exec_())

